<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SMGEditor.PluginApi\SMGEditor.PluginApi.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\src\SMGEditor.Core\SMGEditor.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1">
      <ExcludeAssets>runtime;native</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
