namespace SMGEditor.Core.Stage;

public sealed record GeneralPosNameEntry(string RawName, string FriendlyName, string Games, string Notes);

public static class GeneralPosCatalog
{
    public static IReadOnlyList<GeneralPosNameEntry> Entries { get; } = new GeneralPosNameEntry[]
    {
        new("MarioDemoPos", "Mario demo position", "SMG1", ""),
        new("MarioDemoPos2", "Mario demo position 2", "SMG1", ""),
        new("MarioDemoPos3", "Mario demo position 3", "SMG1", ""),
        new("MarioDemoPos4", "Mario demo position 4", "SMG1", ""),
        new("TicoDemoPos1", "Luma demo position 1", "SMG1", ""),
        new("TicoDemoPos2", "Luma demo position 2", "SMG1", ""),
        new("TicoDemoPos3", "Luma demo position 3", "SMG1", ""),
        new("いいえ選択移動位置", "\"No\" choice move position", "SMG1", ""),
        new("アイテム惑星戻り", "Return to item planet", "SMG2", ""),
        new("ウォーターバズーカマリオ位置", "Water bazooka Mario position", "SMG1", ""),
        new("エピローグマリオ", "Epilogue Mario", "SMG1", ""),
        new("カメラ基準点", "Camera reference point", "SMG2", ""),
        new("ガード出現ポイント1", "Guard spawn point 1", "SMG1", ""),
        new("キノピオメッセンジャー", "Toad messenger", "SMG1", ""),
        new("キングトッシンデモ開始位置", "King Tossin' demo start position", "SMG2", ""),
        new("クッパ階段戦の砲弾出現", "Bowser staircase-battle cannonball spawn", "SMG1", ""),
        new("クッパＪｒシップ戦マリオ位置", "Bowser Jr. ship-battle Mario position", "SMG1", ""),
        new("グランドスター出現", "Grand Star appears", "SMG1", ""),
        new("グランドスター出現位置", "Grand Star appearance position", "SMG2", ""),
        new("グランドスター帰還リザルト", "Grand Star return result", "SMG1", ""),
        new("ゲート中心", "Gate center", "SMG2", ""),
        new("ゲーム終了位置", "Game end position", "SMG2", ""),
        new("ゲーム開始位置", "Game start position", "SMG2", ""),
        new("コア中心", "Core center", "SMG1", ""),
        new("コンプリートエンディングデモ基準点", "Complete-ending demo reference point", "SMG2", ""),
        new("コーチチュートリアル位置", "Coach tutorial position", "SMG1", ""),
        new("コーチレース終了後位置", "Coach post-race position", "SMG1", ""),
        new("コーチ２回目位置", "Coach second-time position", "SMG1", ""),
        new("ゴーストデモゴースト位置", "Ghost demo ghost position", "SMG1", ""),
        new("ゴーストデモマリオ位置", "Ghost demo Mario position", "SMG1", ""),
        new("ジュゲム突進点１", "Lakitu charge point 1", "SMG2", ""),
        new("ジュゲム突進点２", "Lakitu charge point 2", "SMG2", ""),
        new("スターゲットデモ座標", "Star Get demo coordinate", "SMG2", ""),
        new("スタートカメラマリオ座標", "Start-camera Mario coordinate", "SMG1", ""),
        new("スタート位置（サーフィン）", "Start position (surfing)", "SMG1", ""),
        new("スピンドライバ初出基準点", "Spin Driver first-appearance reference point", "SMG2", ""),
        new("スピンドライバ初出終了位置", "Spin Driver first-appearance end position", "SMG2", ""),
        new("タイムアタック前位置", "Pre-time-attack position", "SMG2", ""),
        new("タイムアタック後位置", "Post-time-attack position", "SMG2", ""),
        new("ダウンデモ", "Defeat demo", "SMG1", ""),
        new("ダウンデモ後（マリオ）", "After defeat demo (Mario)", "SMG1", ""),
        new("チュートリアル位置", "Tutorial position", "SMG2", ""),
        new("デモ中心", "Demo center", "SMG1", ""),
        new("デモ位置（クッパＪｒ登場デモ）", "Demo position (Bowser Jr. entrance)", "SMG2", ""),
        new("ドドリュウ再セット", "Bouldergeist reset", "SMG1+SMG2", ""),
        new("ドドリュウ岩", "Bouldergeist rock", "SMG1+SMG2", ""),
        new("ドーム中心", "Dome center", "SMG1", ""),
        new("ノーマルエンディングデモ基準点", "Normal-ending demo reference point", "SMG2", ""),
        new("ハニークイーンとの会話位置", "Conversation position with Queen Bee", "SMG1", ""),
        new("バッタンキング基準位置", "Whomp King reference position", "SMG2", ""),
        new("バトラーデモ終了", "Butler demo end", "SMG1", ""),
        new("バトラーマップレクチャー", "Butler map lecture", "SMG1", ""),
        new("バトルシップ・タイムアタック前位置", "Battleship time-attack pre-position", "SMG1", ""),
        new("バトルシップ・タイムアタック後位置", "Battleship time-attack post-position", "SMG1", ""),
        new("パマタリアンハンターデモ用", "For Pamatarian-hunter demo", "SMG2", ""),
        new("パワーアップデモ（クッパ）", "Power-up demo (Bowser)", "SMG1", ""),
        new("パワーアップデモ（マリオ）", "Power-up demo (Mario)", "SMG1", ""),
        new("パワーアップデモＬｖ２（クッパ）", "Power-up demo Lv2 (Bowser)", "SMG1", ""),
        new("パワーアップデモＬｖ２（マリオ）", "Power-up demo Lv2 (Mario)", "SMG1", ""),
        new("パワーアップデモＬｖ３（クッパ）", "Power-up demo Lv3 (Bowser)", "SMG1", ""),
        new("パワーアップデモＬｖ３（マリオ）", "Power-up demo Lv3 (Mario)", "SMG1", ""),
        new("ピーチャンレーサーレース終了後位置", "Peachy racer post-race position", "SMG2", ""),
        new("ピーチャン位置[スター渡し]", "Peachy position [Star handoff]", "SMG2", ""),
        new("ピーチ登場デモ後（マリオ）", "After Peach entrance demo (Mario)", "SMG1", ""),
        new("ピーチ誘拐デモ基準点", "Peach kidnapping demo reference point", "SMG2", ""),
        new("ピーチ誘拐デモ終了位置", "Peach kidnapping demo end position", "SMG2", ""),
        new("プレイヤーデモ位置（ベビーディノパックン戦）", "Player demo position (Baby Dino Piranha battle)", "SMG2", ""),
        new("プレイヤーデモ位置（ベリードラゴン戦）", "Player demo position (Belly Dragon battle)", "SMG2", ""),
        new("プレイヤー一時退避", "Player temporary evacuation", "SMG2", ""),
        new("ベビチコ出会い点", "Baby Luma meeting point", "SMG2", ""),
        new("ベビーディノパックンデモ位置", "Baby Dino Piranha demo position", "SMG2", ""),
        new("ペンギン移動後", "After penguin moves", "SMG1", ""),
        new("ボスジュゲムダウンデモ位置", "Boss Lakitu defeat demo position", "SMG2", ""),
        new("ボスジュゲムデモ位置", "Boss Lakitu demo position", "SMG2", ""),
        new("ボスブッスン位置", "Boss Bussun position", "SMG2", ""),
        new("ボス戦デモ開始位置", "Boss-battle demo start position", "SMG2", ""),
        new("ポルタデモプレイヤー位置", "Porta demo player position", "SMG1+SMG2", ""),
        new("ポルタ開始デモプレイヤー位置", "Porta start-demo player position", "SMG1+SMG2", ""),
        new("マイスター位置[NPC紹介]", "Meister position [NPC intro]", "SMG2", ""),
        new("マイスター位置[グランドスター帰還後]", "Meister position [after Grand Star return]", "SMG2", ""),
        new("マイスター位置[デフォルト]", "Meister position [default]", "SMG2", ""),
        new("マイスター位置[変化前]", "Meister position [before change]", "SMG2", ""),
        new("マイスター位置[変化後]", "Meister position [after change]", "SMG2", ""),
        new("マイスター位置[帰還後アイテム惑星]", "Meister position [item planet, after return]", "SMG2", ""),
        new("マリオイベント会話", "Mario event conversation", "SMG1", ""),
        new("マリオイベント会話２", "Mario event conversation 2", "SMG1", ""),
        new("マリオイベント会話３", "Mario event conversation 3", "SMG1", ""),
        new("マリオデモ位置", "Mario demo position (generic)", "SMG2", ""),
        new("マリオボスべー対決", "Mario vs. Boss Bee duel", "SMG1", ""),
        new("マリオ位置", "Mario position", "SMG1+SMG2", ""),
        new("マリオ位置00空01", "Mario position 00 / sky 01", "SMG2", ""),
        new("マリオ位置01空00", "Mario position 01 / sky 00", "SMG2", ""),
        new("マリオ位置02空03", "Mario position 02 / sky 03", "SMG2", ""),
        new("マリオ位置03空00", "Mario position 03 / sky 00", "SMG2", ""),
        new("マリオ位置04空03", "Mario position 04 / sky 03", "SMG2", ""),
        new("マリオ位置05空02", "Mario position 05 / sky 02", "SMG2", ""),
        new("マリオ位置06空02", "Mario position 06 / sky 02", "SMG2", ""),
        new("マリオ位置07空04", "Mario position 07 / sky 04", "SMG2", ""),
        new("マリオ位置08空01", "Mario position 08 / sky 01", "SMG2", ""),
        new("マリオ位置[NPC紹介]", "Mario position [NPC intro]", "SMG2", ""),
        new("マリオ位置[でしゃばりルイージ]", "Mario position [meddling Luigi]", "SMG2", ""),
        new("マリオ位置[アイテム惑星移動後]", "Mario position [after moving to item planet]", "SMG2", ""),
        new("マリオ位置[グランドスター帰還後]", "Mario position [after Grand Star return]", "SMG2", ""),
        new("マリオ位置[デモ中]", "Mario position [during demo]", "SMG2", ""),
        new("マリオ位置[デモ後]", "Mario position [after demo]", "SMG2", ""),
        new("マリオ位置[ハラペコスターピースチコ]", "Mario position [Hungry Luma Star Bits]", "SMG2", ""),
        new("マリオ位置[ファイルセレクトから]", "Mario position [from file select]", "SMG2", ""),
        new("マリオ位置[ワールドマップから]", "Mario position [from world map]", "SMG2", ""),
        new("マリオ位置[再スタート]", "Mario position [restart]", "SMG2", ""),
        new("マリオ位置[変化前]", "Mario position [before change]", "SMG2", ""),
        new("マリオ位置[変化後]", "Mario position [after change]", "SMG2", ""),
        new("マリオ位置[帰還]", "Mario position [return]", "SMG2", ""),
        new("マリオ位置[帰還後アイテム惑星]", "Mario position [item planet, after return]", "SMG2", ""),
        new("マリオ位置[帰還後位置上]", "Mario position [above the return position]", "SMG2", ""),
        new("マリオ位置[郵便屋さんイベント]", "Mario position [Mailtoad event]", "SMG2", ""),
        new("マリオ再セット", "Mario reset", "SMG1+SMG2", ""),
        new("マリオ再セット1", "Mario reset 1", "SMG1+SMG2", ""),
        new("マリオ再セット2", "Mario reset 2", "SMG1+SMG2", ""),
        new("マリオ再セット3", "Mario reset 3", "SMG1+SMG2", ""),
        new("マリオ再セット4", "Mario reset 4", "SMG1+SMG2", ""),
        new("マリオ再セット位置", "Mario reset position", "SMG1", ""),
        new("マリオ再セット位置1", "Mario reset position 1", "SMG1", ""),
        new("マリオ再セット位置2", "Mario reset position 2", "SMG1", ""),
        new("マリオ最終デモ終了後位置", "Mario position after final demo", "SMG2", ""),
        new("マリオ最終戦開始位置", "Mario final-battle start position", "SMG2", ""),
        new("マリオ移動後", "After Mario moves", "SMG1", ""),
        new("マリオ顔惑星煙突出口", "Mario's Face planet chimney exit", "SMG2", ""),
        new("メラキンデモ後セット位置", "Set position after Merakin demo", "SMG1", ""),
        new("メラキンマリオ再セット位置", "Merakin Mario reset position", "SMG1", ""),
        new("モンテ投げターゲット位置", "Pianta throw-target position", "SMG2", ""),
        new("ヨッシー出会いデモ基準点", "Yoshi meeting demo reference point", "SMG2", ""),
        new("ヨッシー出会いデモ後マリオ位置", "Mario position after Yoshi meeting demo", "SMG2", ""),
        new("リスタート", "Restart", "SMG1", ""),
        new("ルイージ帰還", "Luigi return", "SMG2", ""),
        new("レース終了後位置", "Post-race position", "SMG1+SMG2", ""),
        new("レース終了後位置テレサ", "Post-race position (Boo)", "SMG1", ""),
        new("レース開始時マリオ位置", "Mario position at race start", "SMG1+SMG2", ""),
        new("ロゼッタ状況説明マリオ", "Rosalina briefing - Mario position", "SMG1", ""),
        new("ワープ位置（サーフィン）", "Warp position (surfing)", "SMG1", ""),
        new("二脚ボス爆発デモ後座標", "Coordinate after biped-boss explosion demo", "SMG2", ""),
        new("合体ブロック故郷点", "Assembly Block home point", "SMG1+SMG2", ""),
        new("図書室中心", "Library center", "SMG1", ""),
        new("子連れカメムシデモ後ポイント", "Point after child-carrying stink bug demo", "SMG1+SMG2", ""),
        new("惑星中心", "Planet center", "SMG1", ""),
        new("惑星Ｌｖ２", "Planet Lv2", "SMG1", ""),
        new("惑星Ｌｖ３", "Planet Lv3", "SMG1", ""),
        new("戦闘開始（クッパ）", "Battle start (Bowser)", "SMG1", ""),
        new("戦闘開始（マリオ）", "Battle start (Mario)", "SMG1", ""),
        new("朗読デモ終了", "Storybook-reading demo end", "SMG1", ""),
        new("未入力", "Blank (unentered)", "SMG1", ""),
        new("爆破デモ後マリオ", "Mario after demolition demo", "SMG1", ""),
        new("着弾点0", "Impact point 0", "SMG2", ""),
        new("着弾点1", "Impact point 1", "SMG2", ""),
        new("着弾点10", "Impact point 10", "SMG2", ""),
        new("着弾点2", "Impact point 2", "SMG2", ""),
        new("着弾点3", "Impact point 3", "SMG2", ""),
        new("着弾点4", "Impact point 4", "SMG2", ""),
        new("着弾点5", "Impact point 5", "SMG2", ""),
        new("着弾点6", "Impact point 6", "SMG2", ""),
        new("着弾点7", "Impact point 7", "SMG2", ""),
        new("着弾点8", "Impact point 8", "SMG2", ""),
        new("着弾点9", "Impact point 9", "SMG2", ""),
        new("絵本移動ポイント000", "Picture-book move point 000", "SMG2", ""),
        new("絵本移動ポイント001", "Picture-book move point 001", "SMG2", ""),
        new("絵本移動ポイント002", "Picture-book move point 002", "SMG2", ""),
        new("落下点1", "Fall point 1", "SMG1", ""),
        new("落下点2", "Fall point 2", "SMG1", ""),
        new("落下点3", "Fall point 3", "SMG1", ""),
        new("落下点4", "Fall point 4", "SMG1", ""),
        new("落下点5", "Fall point 5", "SMG1", ""),
        new("負け時マリオ位置", "Mario position on loss", "SMG1", ""),
        new("開始デモ", "Opening demo", "SMG2", ""),
        new("開始マリオ", "Starting Mario", "SMG1", ""),
        new("階段の戦い０（クッパ）", "Staircase battle 0 (Bowser)", "SMG1", ""),
        new("階段の戦い１（クッパ）", "Staircase battle 1 (Bowser)", "SMG1", ""),
        new("階段の戦い２（クッパ）", "Staircase battle 2 (Bowser)", "SMG1", ""),
        new("隠れ位置", "Hidden position", "SMG1", ""),
        new("Ｌｖ１終了（クッパ）", "Lv1 end (Bowser)", "SMG1", ""),
        new("Ｌｖ１終了（マリオ）", "Lv1 end (Mario)", "SMG1", ""),
        new("Ｌｖ１開始（クッパ）", "Lv1 start (Bowser)", "SMG1", ""),
        new("Ｌｖ１開始（マリオ）", "Lv1 start (Mario)", "SMG1", ""),
        new("Ｌｖ２終了（クッパ）", "Lv2 end (Bowser)", "SMG1", ""),
        new("Ｌｖ２終了（マリオ）", "Lv2 end (Mario)", "SMG1", ""),
        new("Ｌｖ２開始（クッパ）", "Lv2 start (Bowser)", "SMG1", ""),
        new("Ｌｖ２開始（マリオ）", "Lv2 start (Mario)", "SMG1", ""),
        new("Ｌｖ３内側（クッパ）", "Lv3 inner (Bowser)", "SMG1", ""),
        new("Ｌｖ３内側（マリオ）", "Lv3 inner (Mario)", "SMG1", ""),
        new("Ｌｖ３外側（クッパ）", "Lv3 outer (Bowser)", "SMG1", ""),
        new("Ｌｖ３外側（マリオ）", "Lv3 outer (Mario)", "SMG1", ""),
    };

    private static readonly Dictionary<string, GeneralPosNameEntry> ByRawName =
        Entries.ToDictionary(e => e.RawName, StringComparer.Ordinal);

    public static string Friendly(string rawName) =>
        ByRawName.TryGetValue(rawName, out GeneralPosNameEntry? entry) && entry.FriendlyName.Length > 0
            ? entry.FriendlyName
            : rawName;

    public static GeneralPosNameEntry? Find(string rawName) =>
        ByRawName.TryGetValue(rawName, out GeneralPosNameEntry? entry) ? entry : null;
}
