namespace SMGEditor.Core.Stage;

public sealed record ScenarioListEntry(string Key, string Display, int Game);

public static class ScenarioLookupTables
{
    public static IReadOnlyList<ScenarioListEntry> CometTypes { get; } =
    [
        new("", "None", 0),
        new("Red", "Speedrun", 0),
        new("Dark", "Daredevil", 0),
        new("Purple", "Purple Coins", 0),
        new("Black", "Timed Purple Coins", 1),
        new("Exterminate", "Romp", 2),
        new("Mimic", "Cosmic Clones", 2),
        new("Ghost", "Cosmic Race", 1),
        new("Quick", "Fast Foes", 1),
        new("Quick", "Double Time", 2),
    ];

    public static IReadOnlyList<ScenarioListEntry> AppearPowerStarObjTypes { get; } =
    [
        new("", "None", 0),
        new("ディノパックン", "Dino Piranha", 1),
        new("ディノパックンVs2", "Fiery Dino Piranha", 0),
        new("オタキング", "King Kaliente", 1),
        new("ボスカメムシ", "Bugaboom", 0),
        new("ボスベーゴマン", "Topmaniac", 1),
        new("トゥームスパイダー", "Tarantox", 1),
        new("ボスカメック", "Kamella (Space Junk)", 1),
        new("ボスカメック2", "Kamella (Deep Dark)", 1),
        new("ポルタ", "Bouldergeist", 1),
        new("アイスメラメラキング", "Baron Brr", 1),
        new("ドドリュウ", "Major Burrows", 1),
        new("スカルシャーク", "Kingfin", 1),
        new("ウォーターバズーカ", "Underground Gunner (Water)", 1),
        new("エレクトリックバズーカ", "Underground Gunner (Electric)", 1),
        new("メカクッパパーツヘッド", "Mecha Bowser", 1),
        new("クッパ大王（ＶＳ１）", "Bowser (Fountain)", 1),
        new("クッパ大王（ＶＳ２）", "Bowser (Bedroom)", 1),
        new("クッパ大王（ＶＳ３）", "Bowser (Center of the Universe)", 1),
        new("三脚ボス", "Megaleg", 1),
        new("クッパＪｒシップ", "Bowser Jr's Airship", 1),
        new("ベビーディノパックン", "Peewee Piranha", 2),
        new("ボスジュゲム", "Giga Lakitu", 2),
        new("二脚ボス", "Digga-Leg", 2),
        new("キングトッシン", "Rollodillo", 2),
        new("ユッキーナ", "Sorbetti", 2),
        new("ボスブッスン", "Glamdozer", 2),
        new("サンディー", "Squizzard", 2),
        new("オタロックタンク", "Prince Pikante", 2),
        new("バッタンキング", "King Whomp", 2),
        new("ベリードラゴン", "Gobblegut", 2),
        new("ベリードラゴンＬｖ２", "Fiery Gobblegut", 2),
        new("クッパJrロボット", "Megahammer", 2),
        new("クッパJrキャッスル", "Boomsday Machine", 2),
        new("クッパ", "Bowser (W2)", 2),
        new("クッパLv2", "Bowser (W4)", 2),
        new("クッパLv3", "Bowser (W6)", 2),
        new("子連れカメムシ", "Mandibug Stack", 0),
        new("雪像クッパ", "Snow Bowser Statue", 2),
        new("ゴールドワンワン", "Golden Chomp", 0),
        new("テレサチーフ", "Chief Boo", 0),
        new("巨大テレサ", "Big Boo", 2),
        new("ロゼッタ", "Rosalina", 2),
        new("キノピオ", "Toad", 0),
        new("天文台用キノピオ", "Toad (Comet Observatory)", 1),
        new("モック", "Whittle", 2),
        new("パマタリアン", "Gearmo", 0),
        new("パマタリアンハンター", "Gearmo Hunter", 2),
        new("シャッチー", "Guppy (Swimming)", 1),
        new("シャッチー（会話用）", "Guppy (Talking)", 1),
        new("テレサレーサー", "Spooky Speedster", 1),
        new("テレサレーサー", "Spooky Speedster", 2),
        new("ペンギンレーサーリーダー", "Penguin Racer Leader", 1),
        new("ペンギンコーチ", "Penguin Coach", 1),
        new("NPC用ルイージ", "Luigi (Ghostly)", 1),
        new("イベント用ルイージ", "Luigi (Good Egg)", 1),
        new("ルイージ会話用NPC", "Luigi", 2),
        new("ピーチャン", "Jibberjay", 2),
        new("ピーチャンレーサー", "Jibberjay Racer", 2),
        new("いたずらウサギ", "Star Bunny Chase", 0),
        new("いたずら幽霊ウサギ", "Ghost Star Bunny Chase", 0),
        new("いたずらウサギ[自由逃走]", "Free Run Star Bunny (Solo)", 1),
        new("いたずらウサギ集め", "Free Run Star Bunny (Multi)", 1),
        new("さすらいの遊び人(通常会話)", "The Chimp (NPC)", 2),
        new("さすらいの遊び人(スコアアタック)", "The Chimp (Score Attack)", 2),
        new("さすらいの遊び人(ムイムイアタック)", "The Chimp (Skating)", 2),
        new("さすらいの遊び人(トゲピンアタック)", "The Chimp (Bowling)", 2),
        new("クリボー全滅チェッカー", "Goomba Extermination Controller", 1),
        new("スカルシャークベイビー全滅チェッカー", "Swimming Gringill Extermination Controller", 1),
        new("メラメラ全滅チェッカー", "Lil' Cinder Extermination Controller", 1),
        new("全滅監視チェッカー[パワースター]", "Extermination Controller", 2),
        new("花さか監視[パワースター]", "Flower Counter", 2),
        new("フリップパネル監視者", "Flipswitch Panel Observer", 0),
        new("クリスタルケージ[小]", "Small Crystal", 0),
        new("クリスタルケージ[中]", "Medium Crystal", 0),
        new("クリスタルケージ[大]", "Large Crystal", 0),
        new("壊れる籠", "Glass Cage", 0),
        new("壊れる籠[大]", "Large Glass Cage", 0),
        new("壊れる籠[回転タイプ]", "Rotating Glass Cage", 0),
        new("木箱", "Wood Crate", 0),
        new("ハテナ木箱", "HatenaWoodBox", 0),
        new("砂上下タワー破壊壁Ａ", "Tall Wood Crate", 0),
        new("砂上下タワー破壊壁Ｂ", "Taller Wood Crate", 0),
        new("ひび割れ宝箱（パワースター）", "Cracked Treasure Chest with Power Star", 1),
        new("タルタコの樽A", "Barrel", 1),
        new("つらら岩", "Stalagmite", 0),
        new("雪ブロック", "Snow Mushroom", 0),
        new("クッパ彫像", "Bowser Statue", 0),
        new("テレサマンション通り抜け穴のフタ", "Ghostly: Breakable Ceiling", 0),
        new("クロックワークハンドル", "Toy Time: Clockwork Handle", 0),
        new("まゆEXキャノン", "Bubble Blast: Cannon Launcher", 0),
        new("沈没船", "Deep Dark: Sunken Ship", 0),
        new("ビー玉惑星", "Marble Watermelon Planet (Deep Dark)", 1),
        new("たまころ", "Star Ball", 2),
        new("チコ集め", "Silver Stars", 1),
        new("チコ集め", "Silver Stars", 2),
        new("音符の妖精", "Rainbow Notes", 0),
        new("１００枚コイン", "Purple Coins (No Comet)", 0),
        new("たまころ[チュートリアル付き]", "Star Ball", 1),
    ];

    public static IEnumerable<ScenarioListEntry> ForGame(this IReadOnlyList<ScenarioListEntry> entries, int game) =>
        entries.Where(e => e.Game == 0 || e.Game == game);
}
