namespace SMGEditor.Editor;

/* easy way to translate camera parameters to their user-friendly names */
internal static class CameraParamCatalog
{
    public static readonly Dictionary<string, string> FieldLabels = new(StringComparer.OrdinalIgnoreCase)
    {
        ["version"] = "Version",
        ["camtype"] = "Type",
        ["string"] = "String",
        ["angleB"] = "Rotation X",
        ["angleA"] = "Rotation Y",
        ["roll"] = "Rotation Z",
        ["dist"] = "Zoom",
        ["fovy"] = "Field of View",
        ["camint"] = "Transition Time",
        ["camendint"] = "End Transition Time",
        ["gndint"] = "Ground Speed (unused in practice)",
        ["num1"] = "Num 1 (type-dependent)",
        ["num2"] = "Num 2 (type-dependent)",
        ["uplay"] = "Max Y",
        ["lplay"] = "Min Y",
        ["pushdelay"] = "Ground Start Move Delay",
        ["pushdelaylow"] = "Air Start Move Delay",
        ["udown"] = "U Down (unused in practice)",
        ["loffset"] = "Front Zoom",
        ["loffsetv"] = "Height Zoom",
        ["upper"] = "Upper Border",
        ["lower"] = "Lower Border",
        ["evfrm"] = "Event Frames",
        ["evpriority"] = "Event Priority",
        ["woffset.X"] = "Fixpoint Offset X",
        ["woffset.Y"] = "Fixpoint Offset Y",
        ["woffset.Z"] = "Fixpoint Offset Z",
        ["wpoint.X"] = "Worldpoint Offset X",
        ["wpoint.Y"] = "Worldpoint Offset Y",
        ["wpoint.Z"] = "Worldpoint Offset Z",
        ["axis.X"] = "Player Offset X",
        ["axis.Y"] = "Player Offset Y",
        ["axis.Z"] = "Player Offset Z",
        ["vpanaxis.X"] = "Vertical Pan Axis X",
        ["vpanaxis.Y"] = "Vertical Pan Axis Y",
        ["vpanaxis.Z"] = "Vertical Pan Axis Z",
        ["vpanuse"] = "Use Vertical Pan Axis",
        ["up.X"] = "Up Axis X",
        ["up.Y"] = "Up Axis Y",
        ["up.Z"] = "Up Axis Z",
        ["flag.noreset"] = "Disable Reset",
        ["flag.nofovy"] = "Disable Field of View",
        ["flag.lofserpoff"] = "Disable Sharp Zoom",
        ["flag.antibluroff"] = "Disable Anti-Blur",
        ["flag.collisionoff"] = "Disable Collision",
        ["flag.subjectiveoff"] = "Disable First Person",
        ["gflag.enableEndErpFrame"] = "Group: Enable End Transition",
        ["gflag.thru"] = "Group: Through",
        ["gflag.camendint"] = "Group: End Transition Speed",
        ["eflag.enableEndErpFrame"] = "Event: Use End Transition",
        ["eflag.enableErpFrame"] = "Event: Use Transition",
    };

    public static string Label(string fieldName) => FieldLabels.TryGetValue(fieldName, out string? label) ? label : fieldName;

    public readonly record struct CameraTypeInfo(string Value, string? Description);

    public static readonly CameraTypeInfo[] CameraTypes =
    [
        new("CAM_TYPE_2D_SLIDE", "Slides 4 ways only (not forward or backward)"),
        new("CAM_TYPE_ANIM", null),
        new("CAM_TYPE_BEHIND_DEBUG", null),
        new("CAM_TYPE_BLACK_HOLE", null),
        new("CAM_TYPE_BOSS_DONKETSU", null),
        new("CAM_TYPE_CHARMED_FIX", null),
        new("CAM_TYPE_CHARMED_VECREG", null),
        new("CAM_TYPE_CHARMED_VECREG_TOWER", null),
        new("CAM_TYPE_CUBE_PLANET", "Allows the camera to rotate to fit the current gravity"),
        new("CAM_TYPE_DEAD", null),
        new("CAM_TYPE_DONKETSU_TEST", null),
        new("CAM_TYPE_DPD", null),
        new("CAM_TYPE_EYEPOS_FIX", "Moves the camera to a fixed location"),
        new("CAM_TYPE_EYEPOS_FIX_THERE", "Freezes the camera in place - only rotates until freed"),
        new("CAM_TYPE_EYE_FIXED_THERE_TEST", null),
        new("CAM_TYPE_FOLLOW", null),
        new("CAM_TYPE_FOO_FIGHTER", "Red Star related"),
        new("CAM_TYPE_FOO_FIGHTER_PLANET", "Red Star related"),
        new("CAM_TYPE_FREEZE", null),
        new("CAM_TYPE_FRONT_AND_BACK", null),
        new("CAM_TYPE_GROUND", null),
        new("CAM_TYPE_ICECUBE_PLANET", null),
        new("CAM_TYPE_INNER_CYLINDER", null),
        new("CAM_TYPE_INWARD_SPHERE", null),
        new("CAM_TYPE_INWARD_TOWER", "Moves around a fixpoint so the fixpoint's X/Z position is never visible (unconfirmed)"),
        new("CAM_TYPE_INWARD_TOWER_TEST", null),
        new("CAM_TYPE_MEDIAN_PLANET", null),
        new("CAM_TYPE_MEDIAN_TOWER", null),
        new("CAM_TYPE_MTXREG_PARALLEL", null),
        new("CAM_TYPE_OBJ_PARALLEL", "Moves based on Mario's position - usually used for flying"),
        new("CAM_TYPE_POINT_FIX", null),
        new("CAM_TYPE_RACE_FOLLOW", null),
        new("CAM_TYPE_RAIL_DEMO", null),
        new("CAM_TYPE_RAIL_FOLLOW", null),
        new("CAM_TYPE_RAIL_WATCH", null),
        new("CAM_TYPE_SLIDER", null),
        new("CAM_TYPE_SPHERE_TRUNDLE", null),
        new("CAM_TYPE_SPIRAL_DEMO", null),
        new("CAM_TYPE_SUBJECTIVE", null),
        new("CAM_TYPE_TALK", "NPC camera"),
        new("CAM_TYPE_TOWER", "Moves around a fixpoint so the fixpoint's X/Z position is always visible"),
        new("CAM_TYPE_TOWER_POS", null),
        new("CAM_TYPE_TRIPOD_PLANET", null),
        new("CAM_TYPE_TRUNDLE", null),
        new("CAM_TYPE_TWISTED_PASSAGE", null),
        new("CAM_TYPE_WATER_FOLLOW", null),
        new("CAM_TYPE_WATER_PLANET", null),
        new("CAM_TYPE_WATER_PLANET_BOSS", null),
        new("CAM_TYPE_WONDER_PLANET", null),
        new("CAM_TYPE_XZ_PARA", "The most basic camera - the default for most of the game"),
    ];
}
